Release V 0.4.0
ASFHyP3/its-live-monitoring pull request #56
Opened 2024-04-11 19:19 UTC by cirrusasf

Off-naider scenes will now be processed and will only be paired with other off-nadir scenes

2024-04-11 19:32 UTC, jhkennedy requested changes
Marking as "Changes Requested" to prevent merging -- :point_down: change is unexpected. I'll more thoroughly review the rest of the PR this afternoon.

2024-04-11 19:32 UTC, jhkennedy commented on landsat/src/main.py
> +    df = df[df.status_code == 'SUCCEEDED']
:thinking: This is an unexpected change. Previously, we deduplicated against *any* job, whether it was PENDING, RUNNING, SUCCEEDED, or FAILED. This change looks like it will submit duplicate jobs for PENDING and RUNNING, which we definitely don't want, and even for FAILED, we'll want to address the failures and re-submit outside of this stack.

2024-04-11 21:51 UTC, cirrusasf commented on landsat/src/main.py
> +    df = df[df.status_code == 'SUCCEEDED']
You are right. I didn't considering the pending and running. We can get rid of the df = df[df.status_code == 'SUCCEEDED'] party.  I would like to tell that df = ([[*job.job_parameters['granules'], *[job.job_id, job.status_code]] for job in jobs],
        columns=['reference', 'secondary', 'job_id', 'status_code'],) 
is necessary. The previous version df includes two columns (reference and secondary), after we do df =df.set_index(['refeence, secondary']), the df becomes empty, which is not what we expect. Because of the empty df, we end of not do any drop from pairs.

2024-04-16 03:54 UTC, jhkennedy requested changes
This release does not handle off-nadir scenes appropriately. 

Using the script below, I've identified a good off-nadir test scene:
```
LC08_L1GT_052119_20220316_20220321_02_T2
```
and the pairs I would expect this release to produce, which I've uploaded in this GeoDataFrame: [off_nadir_test_set.parquet.zip](https://github.com/ASFHyP3/its-live-monitoring/files/14986535/off_nadir_test_set.parquet.zip)

The above parquet should match the return of `get_landsat_pairs_for_reference_scene` for the above reference scene.

I've opened #58 to fix the off-nadir handling -- it's in draft because I still haven't addressed the tests yet.

---

```python
import json
from datetime import timedelta
from pathlib import Path

import pandas as pd
import geopandas as gpd
from tqdm import tqdm

import main

tqdm.pandas()

LANDSAT_TILES_TO_PROCESS = json.loads(Path('landsat/src/landsat_tiles_to_process.json').read_text())


def id_qualifies(scene_id):
    try:
        item = main._get_stac_item(scene_id)
        return main._qualifies_for_processing(item)
    except Exception:
        return False

# USGS's Landsat scene inventory, which has been uncompressed
# https://landsat.usgs.gov/landsat/metadata_service/bulk_metadata_files/LANDSAT_OT_C2_L1.csv.gz
df = pd.read_csv('LANDSAT_OT_C2_L1.csv')

df = df.loc[df['Nadir/Off Nadir'] != 'NADIR']

df['Start Time'] = pd.to_datetime(df['Start Time'], format='ISO8601')
df = df.sort_values(by='Start Time', ascending=False)

df['tile'] = df['Landsat Product Identifier L1'].str.split('_').str[2]
df = df.loc[df.tile.isin(LANDSAT_TILES_TO_PROCESS)]

df['qualifies'] = df['Landsat Product Identifier L1'].progress_apply(id_qualifies)
df = df.loc[df.qualifies]

tile_with_most_pairs = df.groupby('tile').size().agg('idxmax')
tf = df.loc[df.tile == tile_with_most_pairs].copy()

# NOTE: After tile selection!
tf['days_separation'] = tf.iloc[0]['Start Time'] - tf['Start Time']

tf = tf.loc[tf.days_separation <= timedelta(days=main.MAX_PAIR_SEPARATION_IN_DAYS)]

# convert to same pairs df as we'd get if main.get_landsat_pairs_for_reference_scene was working
reference = main._get_stac_item(tf.iloc[0]['Landsat Product Identifier L1'])

features = []
for scene in tf.iloc[1:]['Landsat Product Identifier L1']:
    item = main._get_stac_item(scene)
    feature = item.to_dict()
    feature['properties']['reference'] = reference.id
    feature['properties']['reference_acquisition'] = reference.datetime
    feature['properties']['secondary'] = item.id
    features.append(feature)

pairs = gpd.GeoDataFrame.from_features(features)
pairs['datetime'] = pd.to_datetime(pairs.datetime)

pairs.to_parquet('off_nadir_test_set.parquet')

```

2024-04-16 03:54 UTC, jhkennedy commented on landsat/src/main.py
> +            f'view:off_nadir={reference.properties["view:off_nadir"]}',
It turns out the STAC catalog returns *the off nadir angle*, not a 0/1 or on/off bool, so `view:off_nadir=0` has an angle of 0 meaning on nadir and off nadir scenes have values like `view:off_nadir=14.076` which are floats that vary depending on the satellite's orbital position and not suitable for eqality comparisons. For example:
```python
>>> pairs['view:off_nadir']
reference                                 secondary                               
LC08_L1GT_052119_20220316_20220321_02_T2  LC08_L1GT_052119_20220228_20220308_02_T2    14.049
                                          LC08_L1GT_052119_20220212_20220223_02_T2    14.076
                                          LC08_L1GT_052119_20220127_20220204_02_T2    14.100
                                          LC08_L1GT_052119_20220111_20220123_02_T2    14.120
                                          LC08_L1GT_052119_20211226_20220105_02_T2    14.134
                                          LC08_L1GT_052119_20210225_20210303_02_T2    14.065
                                          LC08_L1GT_052119_20210209_20210302_02_T2    14.092
                                          LC08_L1GT_052119_20210124_20210305_02_T2    14.115
                                          LC08_L1GT_052119_20210108_20210307_02_T2    14.134
                                          LC08_L1GT_052119_20201223_20210310_02_T2    14.147
                                          LC08_L1GT_052119_20201207_20210313_02_T2    14.156
                                          LC08_L1GT_052119_20201121_20210315_02_T2    14.169
Name: view:off_nadir, dtype: float64
```

2024-04-16 03:54 UTC, jhkennedy commented on landsat/src/main.py
> +        return gpd.GeoDataFrame()
Definitely should be logging *why* we're doing an early return

2024-04-16 18:05 UTC, cirrusasf commented on landsat/src/main.py
> +    df = df[df.status_code == 'SUCCEEDED']
I did a demo code myself. and confirm that you are right. I will drop off my unnecessary code.

2024-04-16 19:25 UTC, cirrusasf commented on landsat/src/main.py
> +        return gpd.GeoDataFrame()
If items is empty, that is items=[], the line 117  

```
df['datetime'] = pd.to_datetime(df.datetime)
```
will get error
AttributeError: 'GeoDataFrame' object has no attribute 'datetime'. Did you mean: 'at_time'?

and code will stop there. Using
```
 if len(items) == 0:
        return gpd.GeoDataFrame()
```
guarantees that the function returns a GeoDataFrame.

2024-04-16 19:25 UTC, cirrusasf commented on landsat/src/main.py
> +            f'view:off_nadir={reference.properties["view:off_nadir"]}',
drop the condition in the line 98 in the query
```
f'view:off_nadir={reference.properties["view:off_nadir"]}
```

2024-04-16 19:33 UTC, jhkennedy commented on landsat/src/main.py
> +        return gpd.GeoDataFrame()
> Definitely should be logging why we're doing an early return

@cirrusasf I'm asking for a *log message*. See https://github.com/ASFHyP3/its-live-monitoring/pull/58/files#diff-f1e691de9a2c1d80620f229d268ec64d4acf7d825227c1fd01609dfab9733f3aR105

2024-04-16 20:01 UTC, cirrusasf commented on landsat/src/main.py
> +        return gpd.GeoDataFrame()
Thank you for clarification.

2024-04-19 00:54 UTC, jhkennedy approved these changes

2024-04-19 00:54 UTC, merged